### ISSUE TITLE
Remove dependencies on Spacy and Stanza and use HF's NER

### ISSUE THREAD

**Issue by avisil** [primeqa/primeqa#317]

**Comment by riyazbhat** [comment]
* Nobody is using `spacy` in `Primeqa`.
* `NLTK` is being used at only one place in ```primeqa/qg/metrics/generation_metrics.py```. We can use `huggingface` instead of `NTLK` here.
* Stanza is heavily being used by the QG modules for NER and sentence segmentation. We can't replacing it currently because of the following reasons:
  * Huggigface [NER](https://huggingface.co/dslim/bert-base-NER) has been trained on Conll 2003 dataset which have just 4 NE tags. Stanza on the other hand is trained on Ontonotes and has 18 tags for English and Chinese. Diversity in tag set is necessary for generating diverse questions.
    * A good option to replace Stanza would be to use [WikiNeural](https://huggingface.co/Babelscape/wikineural-multilingual-ner). It supports multilingual NER and Ontonotes NER model for English.
  * Huggingface doesn't provide support for sentence segmentation. Will have to find an alternative.

**Comment by riyazbhat** [comment]
* Removed Spacy and NLTK. The changes  are part of my current PR.
